### ISSUE TITLE
Investigate HTMLDispatcher exception

### ISSUE THREAD

**Issue by shujutech** [shujutech/StApp#82]
19Mar2018 12:55:35 EROR Error in: biz.shujutech.web.HtmlDispatcher
                        java.lang.StringIndexOutOfBoundsException: String index out of range: -1
                        at java.lang.String.substring(String.java:1927)
                        at biz.shujutech.web.HtmlDispatcher.GetFullPath(HtmlDispatcher.java:51)
                        at biz.shujutech.web.HtmlDispatcher.processRequest(HtmlDispatcher.java:142)
                        at biz.shujutech.web.HtmlDispatcher.doGet(HtmlDispatcher.java:93)
                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at biz.shujutech.web.ServletFilterAuthentication.doFilter(ServletFilterAuthentication.java:100)
                        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
                        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
                        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
                        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
                        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
                        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
                        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
                        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                        at java.lang.Thread.run(Thread.java:748)

**Comment by shujutech** [comment]
resolution as #81 error
